### ISSUE TITLE
Projects use the coordinator URL rather than the proxy URL on the UI

### ISSUE THREAD

**Issue by jim-counter** [subquery/indexer-coordinator#84]
This probably works fine when using an IP rather than a reverse proxy and SSL. Note that the blurred URL is pointing to the address of the `indexer_coordinator` container when it should likely be a configuration parameter so that it picks up the external URL for the `indexer_proxy` container.

![image](https://user-images.githubusercontent.com/11335994/235660814-8f1d3d36-98cd-4fcd-9ca8-3bc3f38122c5.png)

The buttons are pushed off the screen by the long URL too.

**Comment by sorcer1122** [comment]
Actually, I am trying to add SSL to this and it is not working (doing it with nginx as reverse proxy and acme.sh bot). When I go to http -> works good. On https it asks me to register my validator again for some reason. Any ideas?
